/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-07-18 10:50:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.model.SchemeMake.PathApi.PathRequest;
import org.model.BaiduMap;
import org.model.settings;
import org.model.SchemeMake.PathApi.PathReturn;
import org.model.SchemeMake.Units.vertex;
import org.model.SchemeMake.Units.edge;
import org.model.SchemeMake.Units.capacity;
import org.model.SchemeMake.PathApi.result.Route;
import org.model.Query;
import java.util.ArrayList;
import java.util.TreeSet;
import java.util.Iterator;

public final class Querier_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


			String power;
			String status;
			String subtitle;
		
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.model.SchemeMake.PathApi.PathRequest");
    _jspx_imports_classes.add("org.model.SchemeMake.Units.capacity");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("org.model.BaiduMap");
    _jspx_imports_classes.add("org.model.SchemeMake.Units.vertex");
    _jspx_imports_classes.add("org.model.settings");
    _jspx_imports_classes.add("org.model.SchemeMake.Units.edge");
    _jspx_imports_classes.add("org.model.Query");
    _jspx_imports_classes.add("org.model.SchemeMake.PathApi.PathReturn");
    _jspx_imports_classes.add("org.model.SchemeMake.PathApi.result.Route");
    _jspx_imports_classes.add("java.util.TreeSet");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>人群疏散系统</title>\r\n");
      out.write("<link href=\"assets/css/bootstrap.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"assets/css/font-awesome.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"assets/js/morris/morris-0.4.3.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"assets/css/custom-styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href='assets/fonts/OpenSans-Regular.ttf' rel='stylesheet'\r\n");
      out.write("\ttype='text/css' />\r\n");
      out.write("<link href='assets/css/SchemeMake/custom.css' rel='stylesheet'\r\n");
      out.write("\ttype='text/css' />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".botton1 {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".botton2 {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t    ");

	String username = null;
	Cookie[] cookies = request.getCookies();
	for (Cookie cookie : cookies) {
		if (cookie.getName().equals("username")) {
			username = cookie.getValue();
		}
	}
	if(username==null){
		out.println("<script>alert('没有权限 ')</script>");
		return;
	}
	
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t");

			for (Cookie cookie : cookies) {
				if (cookie.getName().equals("power")) {
					power = cookie.getValue();
				}
				if (cookie.getName().equals("status")) {
					status = cookie.getValue();
				}
			}
		
      out.write("\r\n");
      out.write("        <nav class=\"navbar navbar-default top-navbar\" role=\"navigation\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".sidebar-collapse\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"#\">人群疏散系统</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"nav navbar-top-links navbar-right\">\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\" aria-expanded=\"false\">\r\n");
      out.write("                        <i class=\"fa fa-user fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-user\">\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-user fa-fw\"></i>用户名:");
      out.print(username );
      out.write("</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"PersonalAreaServlet\"><i class=\"fa fa-gear fa-fw\"></i>个人设置</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li><a href=\"Login.jsp?quit=1\"><i class=\"fa fa-sign-out fa-fw\"></i>退出登录</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- /.dropdown-user -->\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- /.dropdown -->\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!--/. NAV TOP  -->\r\n");
      out.write("        <nav class=\"navbar-default navbar-side\" role=\"navigation\">\r\n");
      out.write("            <div class=\"sidebar-collapse\">\r\n");
      out.write("                <ul class=\"nav\" id=\"main-menu\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"audit.jsp\"><i class=\"fa fa-desktop\"></i> 演练事件审核</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("                        <a href=\"displayer.jsp?Project_id=1\"><i class=\"fa fa-bar-chart-o\"></i> 显示疏散路径</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"SchemeMake.jsp\"><i class=\"fa fa-qrcode\"></i> 人群疏散方案制定</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-table\"></i> 保护演练<span class=\"fa arrow\"></span></a>\r\n");
      out.write("                        <ul class=\"nav nav-second-level\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"人群保护方案制定.html\">人群保护方案制定</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"人群保护方案查看.html\">人群保护方案查看</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"Evaluator.jsp\"><i class=\"fa fa-edit\"></i> 演练评估 </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"active-menu\" href=\"Querier.jsp\"><i class=\"fa fa-sitemap\"></i> 演练事件查询 </a>\r\n");
      out.write("                        \r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-fw fa-file\"></i> 系统管理<span class=\"fa arrow\"></span></a>\r\n");
      out.write("                        <ul class=\"nav nav-second-level\">\r\n");
      out.write("                            ");

                            	if((Integer.parseInt(power)&4)==4){
                            		subtitle="可修改账户信息";
                            		out.print("<li><a href='AccountManageServlet'>账户管理</a></li>");
                            	}
                            
      out.write("\r\n");
      out.write("                            ");

                            	if((Integer.parseInt(power)&2)==2 && status.equals("1")){
                            		subtitle="可修改角色信息";
                            		out.print("<li><a href='RoleManageServlet'>角色管理</a></li>");
                            	}
                            
      out.write("\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"PersonalAreaServlet\">个人主页</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("\t\t<!-- /. NAV SIDE  -->\r\n");
      out.write("\t\t<div id=\"page-wrapper\">\r\n");
      out.write("\t\t\t<div id=\"page-inner\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<h1 class=\"page-header\">\r\n");
      out.write("\t\t\t\t\t\t\t演练事件查询<small>Querier</small>\r\n");
      out.write("\t\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

				String EventID = null;
				String EventName = null;
				String UserID = null;
				String DrillTime = null;
				String pageNum = null;
				String URL = "Querier.jsp?";
				int pages=1;
				int CurrPage=1;
				int nums=1;
				EventID=request.getParameter("EventID");
				EventName=request.getParameter("EventName");
				UserID=request.getParameter("UserID");
				DrillTime=request.getParameter("DrillTime");
				pageNum=request.getParameter("pageNum");
				String sql = "select * from e_event ";
				String sqlnum = "select count(*) from e_event ";
				if(EventID!=null&&!EventID.equals("")&&!EventID.equals("null")){
					sql+="where event_id='"+EventID+"'";
					sqlnum+="where event_id='"+EventID+"'";
					URL+="EventID="+EventID;
				}
				if(EventName!=null&&!EventName.equals("")&&!EventName.equals("null")){
					sql+="where e_name='"+EventName+"'";
					sqlnum+="where e_name='"+EventName+"'";
					URL+="EventName="+EventName;
				}
				if(UserID!=null&&!UserID.equals("")&&!UserID.equals("null")){
					sql+="where recorder='"+UserID+"'";
					sqlnum+="where recorder='"+UserID+"'";
					URL+="UserID="+UserID;
				}
				if(DrillTime!=null&&!DrillTime.equals("")&&!DrillTime.equals("null")){
					sql+="where DrillTime='"+DrillTime+"'";
					sqlnum+="where DrillTime='"+DrillTime+"'";
					URL+="DrillTime="+DrillTime;
				}
				System.out.println(pageNum);
				if(pageNum!=null&&!pageNum.equals("")&&!pageNum.equals("null")){
					CurrPage=Integer.parseInt(pageNum);
					sql += " limit "+Integer.toString((CurrPage-1)*10)+", 10";
				}
				else{
					sql += " limit 0, 10";
				}
				System.out.println(sql);
				System.out.println(URL);
				ArrayList<String[]>ret = Query.runSql(9,sql);
				ArrayList<String[]>num = Query.runSql(1,sqlnum);
				
				if(ret!=null&&ret.size()!=0)
					nums=Integer.parseInt(num.get(0)[1]);
				else{
					nums=1;
				}
				pages=nums/10+1;
				String id1=null;
				String id2=null;
				for(int i=0;i<ret.size();i++){
					id1 = ret.get(i)[4];
					id2 = ret.get(i)[5];
					String sql1 = "select x_coordinate,y_coordinate from point where p_id='"+id1+"'";
					String sql2 = "select x_coordinate,y_coordinate from point where p_id='"+id2+"'";

					ArrayList<String[]>ret1 = Query.runSql(2,sql1);
					ArrayList<String[]>ret2 = Query.runSql(2,sql2);
					if(ret1==null||ret2==null||ret1.size()==0||ret2.size()==0){
			        	out.print("<script>alert('未知记录'); window.location='Querier.jsp'</script>");
			        	out.flush();
			        	return;
					}
					ret.get(i)[4]=ret1.get(0)[1]+","+ret1.get(0)[2];
					ret.get(i)[5]=ret2.get(0)[1]+","+ret1.get(0)[2];
				}
				
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<!-- Advanced Tables -->\r\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">记录</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"dataTables-example_wrapper\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"dataTables_wrapper form-inline\" role=\"grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<form action=\"Querier.jsp\" method=\"GET\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"dataTables-example_filter\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"dataTables_filter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>事件ID:<input autocomplete=\"off\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control input-sm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTables-example\" name=\"EventID\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>事件名称:<input autocomplete=\"off\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control input-sm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTables-example\" name=\"EventName\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>录入者警号:<input autocomplete=\"off\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control input-sm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTables-example\" name=\"UserID\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>演练时间:<input autocomplete=\"off\" type=\"date\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control input-sm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTables-example\" name=\"DrillTime\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label><input autocomplete=\"off\" type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control input-sm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTables-example\" value=\"搜索\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"height:10px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"table table-striped table-bordered table-hover dataTable no-footer\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"dataTables-example\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-describedby=\"dataTables-example_info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr role=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"sorting_asc\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-sort=\"ascending\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-label=\"Rendering engine: activate to sort column ascending\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 200px;\">事件ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"sorting\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-label=\"Browser: activate to sort column ascending\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 295px;\">事件名称</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"sorting\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-label=\"Browser: activate to sort column ascending\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 295px;\">事件类型</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"sorting\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-label=\"Platform(s): activate to sort column ascending\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 275px;\">疏散点</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"sorting\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-label=\"Engine version: activate to sort column ascending\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 168px;\">避难点</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"sorting\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-label=\"CSS grade: activate to sort column ascending\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 119px;\">录入人</th> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"sorting\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-label=\"CSS grade: activate to sort column ascending\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 119px;\">演练时间</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

											for(int i=0;i<ret.size();i++){
												String[] line = ret.get(i);
												out.println("<tr class=\"gradeA odd\">");
												out.println("<td class=\"sorting_1\">"+line[1]+"</td>");
												out.println("<td class=\" \">"+line[2]+"</td>");
												out.println("<td class=\" \">"+line[3]+"</td>");
												out.println("<td class=\"center \">"+line[4]+"</td>");
												out.println("<td class=\"center \">"+line[5]+"</td>");
												out.println("<td class=\"center \">"+line[8]+"</td>");
												out.println("<td class=\"center \">"+line[9]+"</td>");
											}
											
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"dataTables_info\" id=\"dataTables-example_info\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

											int curr=0;
											if(nums>0){
												curr=(pages-1)*10+1;
											}
											int M = 0;
											if(nums>10){
												M=10;
											}
											else M = nums;
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\trole=\"alert\" aria-live=\"polite\" aria-relevant=\"all\">Showing\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(curr );
      out.write(" to ");
      out.print(M );
      out.write(" of ");
      out.print(nums );
      out.write(" entries</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"dataTables_paginate paging_simple_numbers\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"dataTables-example_paginate\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");


												if(CurrPage==1){
													out.println("<li class=\"paginate_button previous disabled\"");
													out.println("aria-controls=\"dataTables-example\" tabindex=\"0\"");
													out.println("id=\"dataTables-example_previous\"><a href=\"#\">Previous</a></li>");
												}
												else{
													out.println("<li class=\"paginate_button previous\"");
													out.println("aria-controls=\"dataTables-example\" tabindex=\"0\"");
													out.println("id=\"dataTables-example_previous\"><a href=\""+URL+"&PageNum="+Integer.toString(CurrPage-1)+"\">Previous</a></li>");
													
												}
												
												for(int i=1;i<=pages;i++){
													if(i==CurrPage){
														out.println("<li class=\"paginate_button active\"");
														out.println("aria-controls=\"dataTables-example\" tabindex=\""+Integer.toString(i)+"\"><a");
													}
													else{
														out.println("<li class=\"paginate_button\"");
														out.println("aria-controls=\"dataTables-example\" tabindex=\""+Integer.toString(i)+"\"><a");
													}
													out.println("href=\""+URL+"&pageNum="+Integer.toString(i)+"\">"+Integer.toString(i)+"</a></li>");
												}
 
													
													if(CurrPage==pages){
														out.println("<li class=\"paginate_button next disabled\"");
													}
													else{
														out.println("<li class=\"paginate_button next\"");
													}
														out.println("aria-controls=\"dataTables-example\" tabindex=\"0\"");
														out.println("id=\"dataTables-example_next\"><a href=\""+URL+"&pageNum="+Integer.toString(CurrPage+1)+"\">Next</a></li>");
														
													
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!--End Advanced Tables -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<footer>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tCopyright &copy; 2016.Company name All rights reserved.<a\r\n");
      out.write("\t\t\t\t\t\t\ttarget=\"_blank\" href=\"http://sc.chinaz.com/moban/\">&#x7F51;&#x9875;&#x6A21;&#x677F;</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</footer>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /. PAGE INNER  -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /. PAGE WRAPPER  -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /. WRAPPER  -->\r\n");
      out.write("\t<!-- JS Scripts-->\r\n");
      out.write("\t<!-- jQuery Js -->\r\n");
      out.write("\t<script src=\"assets/js/jquery-3.1.0.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap Js -->\r\n");
      out.write("\t<script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- Metis Menu Js -->\r\n");
      out.write("\t<script src=\"assets/js/jquery.metisMenu.js\"></script>\r\n");
      out.write("\t<!-- Custom Js -->\r\n");
      out.write("\t<script src=\"assets/js/custom-scripts.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/morris/morris.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/SchemeMake/costom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
